[project]
name = "jwt-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[email]>=0.135.1",
    "mysql-connector-python>=9.6.0",
    "pydantic[email]>=2.12.5",
    "pydantic-settings>=2.11.0",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.22",
    "sqlalchemy>=2.0.48",
    "uvicorn>=0.41.0",
]
